### PR TITLE
Omitted review comments from PR #27

### PR DESCRIPTION
**Pull request by VarIr**
This is a quick follow-up to #27 , where the following comments were missed, unfortunately.

### CODE REVIEW

**Comment by LokiLuciferase** [comment]
Sorry, that one is on me. I needed these changes, saw that the tests worked, and I merged them under the assumption that all comments had been treated yet

**Comment by VarIr** [comment]
No hard feelings. I just do believe these changes improve our code base :)

**Review by LokiLuciferase — APPROVED** [review]
I am shocked I nearly omitted changes that would `black`en our codebase 😁

**Comment by VarIr** [comment]
Together we stand strong. Will you do me the honor to hit the merge button?

**Pull request merged**
